# The MIT License (MIT)
#
# Copyright (c) 2014 Timothy H Lieberman
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE
#
# Author: Tim Lieberman <tim@timdev.com>
#
# A basic "setup a new Debian Linode" role.   Should really only ever be run once, though it's mostly idempotent, since
# it reboots the VPS to pick up any updated kernel stuff.
#
#
#
# You'll want to set up some variables (probably host or inventory vars) in order for this to work:
#
#  ssh_users - list of users and keys, like:
#     ssh_users:
#       - name: bob
#         key: keys/bob_is_rsa.pub
#       - name: alice
#         key: {{ lookup('file', '~/.ssh/id_rsa.pub') }}
#
---

- name: Set hostname
  hostname: "name={{ inventory_hostname }}"

- name: Create user 'ansible'
  user: name=ansible comment="Ansible User" groups=sudo

- name: Add the local user's pub key to authorized_keys
  authorized_key: user=ansible key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

- name: Create users (they can all sudo!)
  user:
    name: "{{ item.name }}"
    groups: sudo
    shell: /bin/bash
    state: present
  with_items: ssh_users

- name: Add user keys to users' accounts
  authorized_key: user={{ item.name }} key="{{ item.key }}"
  with_items: ssh_users


- name: Add users' keys to ansible account
  authorized_key: user=ansible key="{{ item.key }}"
  with_items: ssh_users

- name: tweak /etc/sudoers
  template:
    src: roles/bootstrap-linode/templates/sudoers.j2
    dest: /etc/sudoers
    mode: 0440
    owner: root
    group: root
    validate: '/usr/sbin/visudo -cf %s'
    backup: True

- name: Update to newest debian
  apt: upgrade=dist update_cache=yes

- name: Disallow root SSH access
  action: lineinfile dest=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin no" state=present
  notify: Restart sshd

- name: reboot
  shell: sleep 2s && /sbin/reboot &

- name: wait for the server to go down (reboot)
  local_action: wait_for host={{ inventory_hostname }} port=22 state=stopped

- name: wait for the server to come up
  local_action: wait_for host={{ inventory_hostname }} port=22 delay=30
